language: python
sudo: required
services: docker

os:
    - linux
    - windows

matrix:
    include:
        - os: windows
          dist: 1803-containers
        - os: linux
          dist: xenial

python:
  - 3.6
  - 3.7

env:
  global:
    - CC_TEST_REPORTER_ID=6b6477c13b8278e4b1be45a6056015ca69fb26748ca7b011cb871a566e6312aa

install: pip install -U tox-travis

before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: tox

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jamesmeakin
  password:
    secure: TT7SEAnHlNlKn6AvseadImTKTmGkN93GeXglL8af+pYeiC7yZoEOEKXo48eX8O7huCSfqI92B/B7mOK8YTmriiiGdN7/fqP1WbCzMpacItbDeZce2M4iDSK4x5tXmEAydp+bE/vAaQkDL+HWBCQDY5kuKUhBpKwvlj3mtJt/mRbPWDKem0JMmW2bQTeJIV/gDIz41J4xpe4RD/xPBNbF66vO2PfRb4wTalO2SeHNaEQ5Gxq4zPH3OehHNlwJxYUHykz1bpG5MUfcTtlSprsTPyuJGkkv3DmOzcw9CECmbTsM7WBJXpVlKeKSKTtOEx4XQe+BSHB9ky0EVkHTgnaieQces//3iNpUEHXNUmVqRXD2kNFKarWrFS2UAUuJn93lOIk7xl28wehIKFt6b2c3LTp9NSt23KsSBqqCNuBz0hmNmIn8LExC4Mb7vAfe9j3IUg8mZoA4cc6GZe9el6QJpmWxUGZzlZOMHM75svHzz2XVyQzsc0tOoD+pdUwlcgti8bJGAImMbsBwxR1b46F7DR2VhE14xfU6Sn5e2rqq82c5j2PCfFi2V0Lyj6tNvQyB7oS2l5r4kHkyb0BOFL+VSepUM1b2UCddaoitoGVoPW+I0PNpAzrCropHVdpkYsZep+kvwTNEGFbxsl2ukRec53kX9M3w/51eBYOpYbDdQ6U=
  on:
    tags: true
    repo: comic/evalutils
    python: 3.7
